# Generated by Django 3.1.5 on 2021-01-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Project Manager'), (2, 'Developer'), (3, 'Submiter')], default=1),
            preserve_default=False,
        ),
    ]
