# Generated by Django 3.1.5 on 2021-01-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Project Manager'), (2, 'Developer'), (3, 'Submiter')], default=3),
        ),
    ]
