# Generated by Django 3.1.5 on 2021-01-10 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0004_auto_20210110_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TickerHistory',
            new_name='TicketHistory',
        ),
    ]
