# Generated by Django 3.1.5 on 2021-01-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210110_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='new_value',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='old_value',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
