# Generated by Django 3.1.5 on 2021-01-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20210110_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=None)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketfiles', to='tracker.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketFilesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('ticketfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketfilecoment', to='tracker.ticketfiles')),
            ],
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketcoment', to='tracker.ticket')),
            ],
        ),
    ]
