# Generated by Django 3.1.5 on 2021-01-10 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0008_auto_20210110_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to='accounts.account'),
            preserve_default=False,
        ),
    ]
