# Generated by Django 3.1.5 on 2021-01-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_ticketcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
