# Generated by Django 3.1.5 on 2021-01-10 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_ticketcomment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Assigned'), (3, 'In Progress'), (4, 'Done')], default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickettag', to='tracker.tickettag'),
        ),
    ]
