# Generated by Django 3.1.5 on 2021-01-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20210110_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickettag', to='tracker.tickettag'),
            preserve_default=False,
        ),
    ]
