# Generated by Django 3.1.5 on 2021-01-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20210110_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
