# Generated by Django 3.1.5 on 2021-01-12 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0013_auto_20210110_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userassigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
